name: Go Typecheck Workflow Test

on: [push, pull_request]

jobs:
  comment-language-detector:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Code Language Detector
        uses: kubecub/typecheck@main